### ISSUE TITLE
Error when deserializing audit log response

### ISSUE THREAD

**Issue by killergerbah** [Discord4J/discord-json#118]
Running this code: 
```
        memberLeaveEvent.getClient().rest().getAuditLogService()
                .getAuditLog(memberLeaveEvent.getGuildId().asLong(), Collections.emptyMap())
                .subscribe(auditLog -> {
                        logger.info("auditLog={}", auditLog);
                });
```

resulted in this error:

```
09:33:35.777 [boundedElastic-2] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableIntegrationData`, problem: Cannot build IntegrationData, some of required attributes are not set [enabled]
 at [Source: (byte[])"{"audit_log_entries": [{"id": "********", "user_id": "********", "target_id": "********", "action_type": 20}, {"id": "********", "user_id": "********", "target_id": "********", "action_type": 28}, {"id": "********", "user_id": "********", "target_id": "********", "action_type": 80, "changes": [{"key": "type", "new_value": "discord"}]}, {"id": "********", "user_id": "********", "target_id""[truncated 18582 bytes]; line: 1, column: 12685] (through reference chain: discord4j.discordjson.json.ImmutableAuditLogData$Json["integrations"]->java.util.ArrayList[0])
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableIntegrationData`, problem: Cannot build IntegrationData, some of required attributes are not set [enabled]
 at [Source: (byte[])"{"audit_log_entries": [{"id": "********", "user_id": "********", "target_id": "********", "action_type": 20}, {"id": "********", "user_id": "********", "target_id": "********", "action_type": 28}, {"id": "********", "user_id": "929066667387011104", "target_id": "********", "action_type": 80, "changes": [{"key": "type", "new_value": "discord"}]}, {"id": "********", "user_id": "********", "target_id""[truncated 18582 bytes]; line: 1, column: 12685] (through reference chain: discord4j.discordjson.json.ImmutableAuditLogData$Json["integrations"]->java.util.ArrayList[0])
	at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Body from GET /guilds/930254044868542484/audit-logs [ClientResponse]
Original Stack Trace:
		at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74)
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
		at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
		at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:702)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Doc94** [comment]
Can you try use the endpoint `/guilds/930254044868542484/audit-logs` and give what returns, the error tell about a missing var but the var mentiones "enabled" based in discord docs its not optional...

**Comment by Doc94** [comment]
Related to https://github.com/discord/discord-api-docs/issues/4802
the field enabled not show in all cases (docs not says this) then for this cases the json cannot be parsed correctly...

**Comment by killergerbah** [comment]
Hi, apologies for the lateness by here's a snippet of the payload that confirms your finding.

```
{
	"audit_log_entries": [...],
	"users": [...],
	"integrations": [{
		"id": "***"",
		"type": "discord",
		"name": "rj-test-2",
		"account": {
			"id": "***"",
			"name": "rj-test-2"
		},
		"application_id": "***""
	}],
	"webhooks": [],
	"guild_scheduled_events": [],
	"threads": [{
		"id": "***"",
		"guild_id": "***"",
		"parent_id": "***"",
		"owner_id": "***"",
		"type": 11,
		"name": "***"",
		"last_message_id": "***"",
		"thread_metadata": {
			"archived": true,
			"archive_timestamp": "2022-04-12T19:02:56.724000+00:00",
			"auto_archive_duration": 60,
			"locked": false,
			"create_timestamp": "2022-04-12T17:19:38.241000+00:00"
		},
		"message_count": 3,
		"member_count": 2,
		"rate_limit_per_user": 0,
		"flags": 0
	}, 
        ...],
	"application_commands": []
}
```

**Comment by Doc94** [comment]
> Hi, apologies for the lateness by here's a snippet of the payload that confirms your finding.
> 
> ```
> {
> 	"audit_log_entries": [...],
> 	"users": [...],
> 	"integrations": [{
> 		"id": "***"",
> 		"type": "discord",
> 		"name": "rj-test-2",
> 		"account": {
> 			"id": "***"",
> 			"name": "rj-test-2"
> 		},
> 		"application_id": "***""
> 	}],
> 	"webhooks": [],
> 	"guild_scheduled_events": [],
> 	"threads": [{
> 		"id": "***"",
> 		"guild_id": "***"",
> 		"parent_id": "***"",
> 		"owner_id": "***"",
> 		"type": 11,
> 		"name": "***"",
> 		"last_message_id": "***"",
> 		"thread_metadata": {
> 			"archived": true,
> 			"archive_timestamp": "2022-04-12T19:02:56.724000+00:00",
> 			"auto_archive_duration": 60,
> 			"locked": false,
> 			"create_timestamp": "2022-04-12T17:19:38.241000+00:00"
> 		},
> 		"message_count": 3,
> 		"member_count": 2,
> 		"rate_limit_per_user": 0,
> 		"flags": 0
> 	}, 
>         ...],
> 	"application_commands": []
> }
> ```

yeah its like discord says.. this type of integration (discord) not has the enabled field... i make a PR for fix this https://github.com/Discord4J/discord-json/pull/119

**Comment by killergerbah** [comment]
Great! I tried your fix in a snapshot and I'm able to parse audit logs response now.
