### ISSUE TITLE
Error when deserialize `GatewayData` in graalvm#native-image runtime-mode

### ISSUE THREAD

**Issue by BOFA1ex** [Discord4J/discord-json#149]
## Produce
use graalvm native-image compile the application which builtin discord4j dep.

## Question
It will delegate on `ImmutableGatewayData#fromJson`, and try to consturct instance of the `Json`.
As i know,  the ImmutableGatewayData$Json was non-public inner-class, so append on reflect-config.json `<init>` was not working.

```json
{
    "name": "discord4j.discordjson.json.ImmutableGatewayData",
    "allDeclaredConstructors": true,
    "allDeclaredFields": true,
    "methods": [
      {
        "name": "isSessionStartLimitPresent",
        "parameterTypes": [ ]
      },
      {
        "name": "sessionStartLimit",
        "parameterTypes": [ ]
      },
      {
        "name": "fromJson",
        "parameterTypes": [
          "discord4j.discordjson.json.ImmutableGatewayData$Json"
        ]
      },
      {
        "name": "isShardsPresent",
        "parameterTypes": [ ]
      },
      {
        "name": "url",
        "parameterTypes": [ ]
      },
      {
        "name": "shards",
        "parameterTypes": [ ]
      }
    ]
  }
```

## Exception
```java
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `discord4j.discordjson.json.ImmutableGatewayData$Json`: cannot deserialize from Object value (no delegate- or property-based Creator): this appears to be a native image, in which case you may need to configure reflection for the class that is to be deserialized
 at [Source: (byte[])"{"url": "wss://gateway.discord.gg", "session_start_limit": {"max_concurrency": 1, "remaining": 988, "reset_after": 28846008, "total": 1000}, "shards": 1}"; line: 1, column: 2]
        at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74) ~[na:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ Body from GET /gateway/bot [ClientResponse]
Original Stack Trace:
                at discord4j.rest.http.JacksonReaderStrategy.lambda$read$0(JacksonReaderStrategy.java:74) ~[na:na]
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[na:na]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128) ~[na:na]

```

**Comment by BOFA1ex** [comment]
https://github.com/immutables/immutables/issues/1446

**Comment by BOFA1ex** [comment]
```json
{
  "name":"discord4j.discordjson.json.ImmutableGatewayData$Json",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[
    {"name":"<init>","parameterTypes":[] }, 
    {"name":"setSessionStartLimit","parameterTypes":["discord4j.discordjson.possible.Possible"] }, 
    {"name":"setShards","parameterTypes":["discord4j.discordjson.possible.Possible"] }, 
    {"name":"setUrl","parameterTypes":["java.lang.String"] }
  ]
}
```

It work!
